apiVersion: v1
kind: Pod
metadata:
  name: pod-ci
  labels:
    app: podci
spec:
  containers:
  - name: my-name
    image: nginx:latest
    ports:
    - containerPort: 8080

#  --- : this indicate one object script is ends here, 
# now we can write another object script in same file 
---
apiVersion: v1
kind: Service
metadata:
  name: ci-service
spec:
  selector:
    app: podci
  type: ClusterIP # (case-sensitive: I must be capital)
  # selector mde apan sangat ahe "app: podci" jo object ahe kiva 
  #  apan mhanu shakto jya pod la pan "podci" ha tag dila ahe tyach 
  # pod la he clusterIp attach krun dya

  # In short clusterip service tyach pod la attach kara jya pod la podci navane key & value attach kelela ahe

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
